### ISSUE TITLE
Bootstrap 3 alerts not showing

### ISSUE THREAD

**Issue by SergiX44** [vinkla/laravel-alert#4]
The class "fade" makes the alert with opacity 0, so it's hidden. Working under bootstrap 4 correctly.

**Comment by vinkla** [comment]
Please make a pull request. Thanks.

**Comment by SergiX44** [comment]
I'II make 2 different views for the 2 different bootstrap version, so that you can decide the correct view according to the bootstrap version in use

**Comment by vinkla** [comment]
Okay, do that and then we can take a look at it.
