### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by nateetk** [vinkla/laravel-alert#7]
i have added in the following and i think it would be very useful to your module:

ability to show multiple messages at once
ability for alerts to fade out automatically which can be on a per message basis

i have placed these changes in the resources/views/bootstrap.blade.php
and the src/Alert.php

[Alert.zip](https://github.com/vinkla/laravel-alert/files/1388365/Alert.zip)

**Comment by nateetk** [comment]
also for the fade out your can use something along the lines of: Alert::error('what the it works 2', true);

**Comment by vinkla** [comment]
Hi @nateetk, thanks for the idea! Before I can take a look at it, please [submit a pull request](https://guides.github.com/activities/hello-world/#pr).
